function to_int(boolan: bool) returns (int);
axiom to_int(true) == 1;
axiom to_int(false) == 0;

procedure contract();
implementation contract(){
  var x: int;
  var y: int;
  var z: int;
  var scratch_slot_1: int;
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);

  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);

  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);

  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);

  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
	x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);
  x := 12;
  y := x;
  z := x * y;
  scratch_slot_1 := z;
  x := 10;
  y := x;
  z := x * y;
  x := scratch_slot_1;
  y := x + z;
  x := 244;
  z := to_int(x == y);

	assert z == 0;
}

